config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:edit,:update,:index] do
  	member do
    	get :follows, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  get 'search/search' #コントローラ名を複数形にし忘れた為
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy #userが消えればbookも消える
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  		   # 架空モデルfollowings　中間テーブルのrelationshipsを通るように　フォローしているuserの取得
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  		   # 1行目の逆を意味する(逆方向)
  has_many :followers, through: :reverse_of_relationships, source: :user
  		   # 架空モデルfollowers　中間テーブルのreverse_of_relationshipsを通るように　フォロワー(user)の取得
  		   # foregin_key = 入口
		     # source = 出口
  # フォロー機能
  attachment :profile_image # attachment :profile_image, destroy: false?
  validates :name, presence: true, length: {in: 2..20} # 2~20文字以内
  validates :introduction, length: {maximum: 50} # 50文字以内

  def follow(other_user)
    unless self == other_user #フォローしようとしているother_userが自分でないか検証している
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user) #フォローがあればアンフォロー
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship #relationshipが存在すればdestroyする
  end

  def following?(other_user)
    self.followings.include?(other_user)
    # フォローしている User 達を取得。other_user が含まれていればtrue,含まれていなければfalseを返す。
  end
    # 検索機能・Userが選択されて、各項目選択時の処理
  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "1"
         User.where(['name LIKE ?', "#{search}"])
      elsif how_search == "2"
         User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "3"
         User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "4"
         User.where(['name LIKE ?', "%#{search}%"])
      else
         User.all
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! #devise側が用意したもの
  before_action :error, only:[:edit, :update]
  #上2つのアクションはそれぞれのアクションを行う前にerrorアクションを行う。
  #よって今回は@user = User.find(params[:id])を2つのアクション内に書く必要がなくなる。

  def show
    @user = User.find(params[:id])
    @book = Book.new #新規投稿 保存はbookコントローラ
    @books = @user.books
  end

  def index
    @user = User.find(current_user.id) #or current_user
    @users = User.all
    @book = Book.new #新規投稿 保存はbookコントローラ
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private
    #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def error
    @user = User.find(params[:id])
    if current_user.id != @user.id
       redirect_to user_path(current_user)
    end
  end

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build) do |f| %>
    <%= hidden_field_tag :follow_id, user.id %>
    <!-- hidden_field_tagは、一個だけパラメータを他のアクションへ単体で渡したい時に使用 -->
    <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
<% end %>

<!-- %= link_to "表示させたい文字", user_relationships_path(user.id), method: :POST % -->
<!-- link_toで作る場合はこれ一行。 -->

app/views/users/_side.html.erb
<div class="col-xs-3">
	<h1>User info</h1>
	<%= attachment_image_tag user, :profile_image, size: "150x150", fallback: "no_image.jpg"%>
	<table width="350">
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th><%= link_to user.followings.count, follows_user_path(user) %></th>
		</tr>

		<tr>
			<th>followers</th>
			<th><%= link_to user.followers.count, followers_user_path(user) %></th>
		</tr>
	</table>

	<% unless current_user == user %>
	    <% if current_user.following?(user) %>
	    	<%= render 'users/unfollow', user: user %>
	  	<% else %>
	    	<%= render 'users/follow', user: user %>
	  	<% end %>
	<% end %>_

	<% if user.id == currentuser.id %>
		<%= link_to edit_user_path(user.id) do %>
			<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> <!-- aria-hiddenは読み飛ばし機能 -->
		<% end %>
	<% end %>

	<h1>New book</h1>

	<% if @book.errors.any? %>
		<%= @book.errors.count %>error prohibited this book from being saved:<br>
			<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	<% end %>

	<%= form_for(book) do |f| %>

		<p>Title</p>
		<%= f.text_field :title, class: "newbook-form" %>

		<p>Opinion</p>
		<%= f.text_area :body, class: "newbook-form" %>

		<input type="submit" value="Create Book" class="newform" >

	<% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
	<%= hidden_field_tag :follow_id, user.id %>
	<!-- hidden_field_tagは、一個だけパラメータを他のアクションへ単体で渡したい時に使用 -->
	<%= f.submit 'フォロー外す', class: 'btn btn-danger btn-block' %>
<% end %>

<!-- %= link_to "表示させたい文字", user_relationships_path(user.id), method: :delete % -->
<!-- link_toで作る場合はこれ一行。 -->

app/views/users/edit.html.erb
<main>
	<h1>User info</h1>

	<% if @user.errors.any? %>
	<%= @user.errors.count %>error prohibited this user from being saved:<br>
		<ul>
		<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	<% end %>

	<%= form_for(@user) do |f| %>
		<p>Name
		<%= f.text_field :name %></p>

		<p>Image</p>
		<!-- 画像選択用のボタン -->
		<%= f.attachment_field :profile_image %> <!-- カラムはprofile_image_idだが、_idは省く -->

		<p>Introduction
		<%= f.text_area :introduction %></p>

		<p><%= f.submit 'Update User' %></p>

	<% end %>
</main>

app/views/users/followers.html.erb
<h1>Follower Users</h1>

<div class="col-xs-9">
	<table class="table table-hover table-inverse" width="600">
		<h1>Users</h1>
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>
		<% @users.each do |user| %>
			<tr align="left">
				<td><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg"%></td>
				<td><%= user.name %></td>
				<td>フォロー数:<%= user.followings.count %></td>
				<td>フォロワー数:<%= user.followers.count %></td>
				<td>
					<% if current_user != user %>
						<% if current_user.following?(user) %>
					    	<%= render 'unfollow', user: user %>
					  	<% else %>
					    	<%= render 'follow', user: user %>
					  	<% end %>
					<% end %>
				</td>
				<td><%= link_to "Show", user_path(user) %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/users/follows.html.erb
<h1>Follow Users</h1>

<div class="col-xs-9">
	<table class="table table-hover table-inverse" width="600">
		<h1>Users</h1>
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>
		<% @users.each do |user| %>
			<tr align="left">
				<td><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg"%></td>
				<td><%= user.name %></td>
				<td>フォロー数:<%= user.followings.count %></td>
				<td>フォロワー数:<%= user.followers.count %></td>
				<td>
					<% if current_user != user %>
						<% if current_user.following?(user) %>
					    	<%= render 'unfollow', user: user %>
					  	<% else %>
					    	<%= render 'follow', user: user %>
					  	<% end %>
					<% end %>
				</td>
				<td><%= link_to "Show", user_path(user) %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<%= render 'users/side', user: @user, book: @book %>

		<div class="col-xs-9">
			<table class="table table-hover table-inverse" width="600">
				<h1>Users</h1>
				<tr>
					<th>image</th>
					<th>name</th>
				</tr>
				<% @users.each do |user| %>
					<tr align="left">
						<td><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg"%></td>
						<td><%= user.name %></td>
						<td>フォロー数:<%= user.followings.count %></td>
						<td>フォロワー数:<%= user.followers.count %></td>
						<td>
							<% if current_user != user %>
								<% if current_user.following?(user) %>
							    	<%= render 'unfollow', user: user %>
							  	<% else %>
							    	<%= render 'follow', user: user %>
							  	<% end %>
							<% end %>
						</td>
						<td><%= link_to "Show", user_path(user) %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<p><%= flash[:notice] %></p>

		<%= render 'users/side', user: @user, book: @book %>

		<div class="col-xs-9">
			<h1>Books</h1>
			<table class="table table-hover table-inverse" width= "600">
				<tr align="left">
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to (book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book) %></td>
						<td><%= book.body %></td>
						<td>コメント数:<%= book.book_comments.count %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>