config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:edit,:update,:index] do
  	member do
    	get :follows, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  get 'search/search' #コントローラ名を複数形にし忘れた為
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user) #各投稿(book)に自分(current_user)のいいね(favorite)がついているか判断する
            favorites.where(user_id: user.id).exists? # exists = 存在
    end

	validates :title, presence: true #空欄
	validates :body, presence: true, length: {maximum: 200} #200文字以内

	  # 検索機能・Userが選択されて、各項目選択時の処理
  	def Book.search(search, user_or_book, how_search)
	  if user_or_book == "2"
	    if how_search == "1"
	       Book.where(['title LIKE ?', "#{search}"])
	    elsif how_search == "2"
	       Book.where(['title LIKE ?', "#{search}%"])
	    elsif how_search == "3"
	       Book.where(['title LIKE ?', "%#{search}"])
	    elsif how_search == "4"
	       Book.where(['title LIKE ?', "%#{search}%"])
	    else
	       Book.all
	    end
	  end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :current_book, only:[:edit, :update]

  def create
    @book = Book.new(book_params) #新規投稿保存。ストロングパラメーターを使用、
    @book.user_id = current_user.id
    if @book.save
       redirect_to book_path(@book), notice: "You have creatad book successfully."
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render "index"
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new #コメント投稿
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book), notice: "You have updated book successfully."
    else
       render "edit"
    end
  end

  def destroy
  	@book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def current_book
    @book = Book.find(params[:id])
    if current_user != @book.user
       redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<main>
	<h1>Editing Book</h1>

	<% if @book.errors.any? %>
	<%= @book.errors.count %>error prohibited this book from being saved:<br>
		<ul>
		<% @book.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	<% end %>

	<%= form_for(@book) do |f| %>
		<p>Title<br>
		<%= f.text_field :title %></p>

		<p>Opinion<br>
		<%= f.text_area :body %></p>

		<%= f.submit 'Update Book' %>

	<% end %>

	<p><%= link_to "Show", book_path(@book.id) %> |
	<%= link_to "Back", books_path %></p>
</main>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<%= render 'users/side', user: @user, book: @book %>

		<div class="col-xs-9">
			<table class="table table-hover table-inverse" width="600">
				<h1>Books</h1>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
				<% @books.each do |book| %>
					<tr align="left">
						<td><%= link_to user_path(book.user.id) do %>
							<%= attachment_image_tag book.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book) %></td>
						<td><%= book.body %></td>
						<td>
							<% if book.favorited_by?(current_user) %> <!-- 投稿本にログインユーザーのいいねがあるかどうか -->
								<%= link_to book_favorites_path(book), method: :delete do %>
									<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
								<% end %>
							<% else %>
								<%= link_to book_favorites_path(book), method: :post do %>
								    <i class="fa fa-heart-o" aria-hidden="true"></i>
								<% end %>
							<% end %>
							<%= book.favorites.count %>
						</td>
						<td>コメント数:<%= book.book_comments.count %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<p><%= flash[:notice] %></p>

		<%= render 'users/side', user: @book.user, book: Book.new %>
		<!-- book: Book.newは裏技。bookコントローラに新しいインスタンス変数 @〇〇 = Book.new を作らなくて済む -->
		<!-- @bookの定義は他ですでにしてある為、違う名前で定義しないといけない。対象箇所(ビュー)も変えなきゃなので手間 -->

		<div class="col-xs-9">
			<table class="table table-hover table-inverse" width="600">
				<h1>Book detail</h1>
				<tr>
					<td>
						<%= link_to user_path(@user) do %>
							<%= attachment_image_tag @user, :profile_image, size: "60x60", fallback: "no_image.jpg" %><br>
							<%= @user.name %> <!-- 本の投稿者の名前 @userはコントローラにて定義済み -->
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>

					<td>
						<% if @book.favorited_by?(current_user) %> <!-- 投稿本にログインユーザーのいいねがあるかどうか -->
							<%= link_to book_favorites_path(@book), method: :delete do %>
								<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
								<%= @book.favorites.count %>
							<% end %>
						<% else %>
							<%= link_to book_favorites_path(@book), method: :post do %>
								 <i class="fa fa-heart-o" aria-hidden="true"></i>
								 <%= @book.favorites.count %>
							<% end %>
						<% end %>
					</td>
					 <td>コメント数:<%= @book.book_comments.count %></td>

					<% if @user == current_user %>
					 <td><%= link_to "Edit", edit_book_path(@book), class: "book-edit book-btn" %></td>
					<% end %>
					<% if @user == current_user %>
						<td><%= link_to "Destroy", book_path(@book), class: "book-destroy book-btn", method: :delete, "data-confirm" => "本当に削しますか？" %></td>
					<% end %>
				</tr>

				<% @book.book_comments.each do |book_comment|  %>
					<tr>
						<td style="border: none;">
							<%= link_to (book_comment.user) do %>
								<%= attachment_image_tag book_comment.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %><br>
								<%= book_comment.user.name %>
							<% end %>
						</td>
						<td style="border: none;">
							<%= book_comment.comment %>
							<% if book_comment.user == current_user %>
								<%= link_to "Destroy", book_book_comment_path(@book, book_comment), class: "book-destroy book-btn", method: :delete, "data-confirm" => "本当に消しますか？" %>
							<% end %>
						</td>
					</tr>
				<% end %>
			</table>

			<% if @book_comment.errors.any? %>
				<%= @book_comment.errors.count %>error prohibited this book_comment from being saved:<br>
					<ul>
					<% @book_comment.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
					</ul>
			<% end %>

			<%= form_for [@book, @book_comment] do |f| %>
				<!-- bookに紐づいたbook_commentだから、配列で２つ書く必要がある -->
				<%= f.text_area :comment, class: "book-comment-form", rows:'5', placeholder: "コメントをここに" %>
				<!--comment, の後ろに次のように書いて広さの指定をする方法もある。size: "90x5" cssが不要になる。%> -->
				<%= f.submit "送信", class: "comment-btn" %>
			<% end %>
		</div>
	</div>
</div>