config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:edit,:update,:index] do
  	member do
    	get :follows, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  get 'search/search' #コントローラ名を複数形にし忘れた為
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers002</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-contents">
        <span class="header-title">Bookers002</span>
        <nav>
          <ul class="nav-list">
            <% if user_signed_in? %>
              <li class="nav-list-item">
                <%= link_to user_path(current_user.id) do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                  Home
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to users_path do %>
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                  Users
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to books_path do %>
                  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                  Books
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                  logout
                <% end %>
              </li>
            <% else %>
              <li class="nav-list-item">
                <%= link_to root_path do %>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                  Home
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to home_about_path do %>
                  <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
                  About
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to new_user_registration_path do %>
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                sign up
                <% end %>
              </li>
              <li class="nav-list-item">
                <%= link_to user_session_path do %>
                  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                  login
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <main>
      <!-- 検索機能 -->
      <div class="search-form">
        <% if user_signed_in? %>
          <%= form_tag(search_search_path, method: :get) do %> <!-- path名 → コントローラ名を複数形にし忘れた為 -->
            <%= text_field_tag :search %> <!-- ワード検索フォーム -->
            <%= select_tag(:option, options_for_select([["User","1"],["Book","2"]])) %>
            <%= select_tag(:choice, options_for_select([["完全一致","1"],["前方一致","2"],["後方一致","3"],["部分一致","4"]])) %>
            <%= submit_tag "検索" %>
          <% end %>
        <% end %>
      </div>
      <!-- 検索機能 -->
      <%= yield %>
    </main>
    <footer>
      <div class="footer-contents">
        CopyRight Infratop.inc
      </div>
    </footer>
  </body>
</html>